apiVersion: v1
kind: Service
metadata:
  name: {{ include "quake.fullname" . }}
  labels:
    {{- include "quake.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "quake.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-game
      port: {{ .Values.service.port }}
      targetPort: http-game
      protocol: TCP
